### PR TITLE
Abuseipdb

### PR DESCRIPTION
**Pull request by Wuemeli**
Hey,

I'm pretty new to go, so don't blame me when some things are not written perfect. But it works. Basically, if activated it will check each IP Address in the Abuse IP Database, and then it blocks the request accordingly. I also added the new config entry in the generator and the example config.

### CODE REVIEW

**Comment by Wuemeli** [comment]
Oh, and please ignore all those commits. My Dev setup for this proxy is that I always push to my branch and pull it from my Server.

**Comment by Wuemeli** [comment]
I will add an auto report feature that reports IP Addresses that are rate limited etc. So please don't merge this yet

**Comment by 41Baloo** [comment]
It's an interesting idea i myself have played around with, sadly it's somewhat flawed. Using this would mean every single request has to wait for the abuseipdb api call to finish. While we can mitigate that slightly by caching the responses, In case of a DDoS attack we'd be sending well over 3.000 Requests (the highest ratelimit on abuseipdb)

> All free accounts have a rate limit of 1,000 reports and checks per day. Webmaster accounts have a rate limit of 3,000 requests/day.

So sadly for now, i don't think this would be a good way to go about things. Maybe i could setup some kind of key-value db that remembers previously ratelimited / ddosing ips to be more strict with them later on

**Comment by Wuemeli** [comment]
Ight. Ima leave this PR open because I'm sure there's an alternative or something similar.

**Comment by 41Baloo** [comment]
Mhm yeah, feel free to reopen it if you find an alternative

**Comment by Wuemeli** [comment]
ight

**Pull request closed without merging**
